apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
  - schedulerName: default-scheduler
extenders:
  - urlPrefix: "http://ml-extender.kube-system.svc.cluster.local:8080"
    filterVerb: "filter"
    prioritizeVerb: "prioritise"
    weight: 5
    enableHTTPS: false
    ignorable: true