apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pass-hash
spec:
  template:
    spec:
      containers:
        - image: kind.local/pass-hash:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080