apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pass-hash
spec:
  template:
    spec:
      containers:
        - image: pass-hash:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Password Hashing"